prompts: ["{{question}}"]
providers:
  - exec:python -m 'aiconfig.eval.promptfoo.run_aiconfig' ./travel_aiconfig_test_suite_settings.json
tests:
  - description: "Test if output is equal to the expected value"
    vars:
      question: Empire State Building is on fifth avenue. What is the cross street?
    assert:
      - type: python
        value: output.lower().find('34th street') != -1
  - description: "Test if output is equal to the expected value"
    vars:
      question: "which is the best borough?"
    assert:
      - type: python
        value: output == "Brooklyn"
